## Step 1: Preprocess the Data

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [2]:
#  Import and read the charity_data.csv.
from google.colab import files
file = files.upload()

Saving charity_data.csv to charity_data.csv

In [3]:
application_df = pd.read_csv("charity_data.csv")
application_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<500].index)
application_types_to_replace
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
counts_binning = application_df['CLASSIFICATION'].value_counts()
counts_binning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
counts_classification = counts_binning[counts_binning>1]
counts_classification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (counts_binning[counts_binning<50].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      391
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [12]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values

X = application_df.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Step 2: Compile, Train, and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train_scaled[0])
hidden_nodes_layer1=15
hidden_nodes_layer2=15
hidden_nodes_layer3=15

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 15)                810

 dense_1 (Dense)             (None, 15)                240

 dense_2 (Dense)             (None, 15)                240

 dense_3 (Dense)             (None, 1)                 16

=================================================================
Total params: 1,306
Trainable params: 1,306
Non-trainable params: 0
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=200)

Epoch 1/200
684/684 [==============================] - 3s 3ms/step - loss: 0.5948 - accuracy: 0.7039 - val_loss: 0.5534 - val_accuracy: 0.7359
Epoch 2/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5584 - accuracy: 0.7253 - val_loss: 0.5480 - val_accuracy: 0.7359
Epoch 3/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7291 - val_loss: 0.5441 - val_accuracy: 0.7378
Epoch 4/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7288 - val_loss: 0.5460 - val_accuracy: 0.7359
Epoch 5/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7305 - val_loss: 0.5436 - val_accuracy: 0.7378
Epoch 6/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7298 - val_loss: 0.5457 - val_accuracy: 0.7370
Epoch 7/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7322 - val_loss: 0.5447 - val_accuracy: 0.7367
Epoch 8/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7304 - val_loss: 0.5423 - val_accuracy: 0.7357
Epoch 9/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7306 - val_loss: 0.5438 - val_accuracy: 0.7365
Epoch 10/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7327 - val_loss: 0.5446 - val_accuracy: 0.7359
Epoch 11/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7322 - val_loss: 0.5441 - val_accuracy: 0.7352
Epoch 12/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7347 - val_loss: 0.5444 - val_accuracy: 0.7328
Epoch 13/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7332 - val_loss: 0.5423 - val_accuracy: 0.7346
Epoch 14/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7331 - val_loss: 0.5436 - val_accuracy: 0.7362
Epoch 15/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7327 - val_loss: 0.5428 - val_accuracy: 0.7344
Epoch 16/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7332 - val_loss: 0.5435 - val_accuracy: 0.7375
Epoch 17/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7337 - val_loss: 0.5408 - val_accuracy: 0.7365
Epoch 18/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7347 - val_loss: 0.5420 - val_accuracy: 0.7326
Epoch 19/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7348 - val_loss: 0.5423 - val_accuracy: 0.7365
Epoch 20/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7348 - val_loss: 0.5433 - val_accuracy: 0.7362
Epoch 21/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7351 - val_loss: 0.5420 - val_accuracy: 0.7370
Epoch 22/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7341 - val_loss: 0.5412 - val_accuracy: 0.7362
Epoch 23/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7347 - val_loss: 0.5418 - val_accuracy: 0.7352
Epoch 24/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7355 - val_loss: 0.5414 - val_accuracy: 0.7375
Epoch 25/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7343 - val_loss: 0.5403 - val_accuracy: 0.7357
Epoch 26/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7345 - val_loss: 0.5413 - val_accuracy: 0.7352
Epoch 27/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7352 - val_loss: 0.5427 - val_accuracy: 0.7334
Epoch 28/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7359 - val_loss: 0.5406 - val_accuracy: 0.7362
Epoch 29/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7358 - val_loss: 0.5401 - val_accuracy: 0.7341
Epoch 30/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7350 - val_loss: 0.5421 - val_accuracy: 0.7354
Epoch 31/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7356 - val_loss: 0.5409 - val_accuracy: 0.7349
Epoch 32/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7352 - val_loss: 0.5421 - val_accuracy: 0.7349
Epoch 33/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7360 - val_loss: 0.5407 - val_accuracy: 0.7346
Epoch 34/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7358 - val_loss: 0.5420 - val_accuracy: 0.7357
Epoch 35/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7365 - val_loss: 0.5412 - val_accuracy: 0.7385
Epoch 36/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7355 - val_loss: 0.5422 - val_accuracy: 0.7367
Epoch 37/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7364 - val_loss: 0.5391 - val_accuracy: 0.7339
Epoch 38/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7363 - val_loss: 0.5412 - val_accuracy: 0.7372
Epoch 39/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7362 - val_loss: 0.5405 - val_accuracy: 0.7349
Epoch 40/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7369 - val_loss: 0.5428 - val_accuracy: 0.7341
Epoch 41/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7366 - val_loss: 0.5401 - val_accuracy: 0.7357
Epoch 42/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7365 - val_loss: 0.5408 - val_accuracy: 0.7359
Epoch 43/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7370 - val_loss: 0.5408 - val_accuracy: 0.7297
Epoch 44/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7357 - val_loss: 0.5403 - val_accuracy: 0.7341
Epoch 45/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7368 - val_loss: 0.5397 - val_accuracy: 0.7375
Epoch 46/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7375 - val_loss: 0.5409 - val_accuracy: 0.7372
Epoch 47/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7369 - val_loss: 0.5408 - val_accuracy: 0.7354
Epoch 48/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7372 - val_loss: 0.5402 - val_accuracy: 0.7354
Epoch 49/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7380 - val_loss: 0.5403 - val_accuracy: 0.7331
Epoch 50/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7359 - val_loss: 0.5426 - val_accuracy: 0.7357
Epoch 51/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7370 - val_loss: 0.5411 - val_accuracy: 0.7346
Epoch 52/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7378 - val_loss: 0.5404 - val_accuracy: 0.7380
Epoch 53/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7370 - val_loss: 0.5410 - val_accuracy: 0.7346
Epoch 54/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7377 - val_loss: 0.5418 - val_accuracy: 0.7378
Epoch 55/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7382 - val_loss: 0.5417 - val_accuracy: 0.7359
Epoch 56/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7376 - val_loss: 0.5401 - val_accuracy: 0.7370
Epoch 57/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7374 - val_loss: 0.5410 - val_accuracy: 0.7357
Epoch 58/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7371 - val_loss: 0.5417 - val_accuracy: 0.7344
Epoch 59/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7372 - val_loss: 0.5423 - val_accuracy: 0.7372
Epoch 60/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7380 - val_loss: 0.5402 - val_accuracy: 0.7339
Epoch 61/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7378 - val_loss: 0.5432 - val_accuracy: 0.7385
Epoch 62/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7379 - val_loss: 0.5433 - val_accuracy: 0.7372
Epoch 63/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7386 - val_loss: 0.5399 - val_accuracy: 0.7362
Epoch 64/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7381 - val_loss: 0.5412 - val_accuracy: 0.7352
Epoch 65/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7380 - val_loss: 0.5421 - val_accuracy: 0.7362
Epoch 66/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7374 - val_loss: 0.5421 - val_accuracy: 0.7349
Epoch 67/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7379 - val_loss: 0.5408 - val_accuracy: 0.7339
Epoch 68/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7378 - val_loss: 0.5417 - val_accuracy: 0.7354
Epoch 69/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7386 - val_loss: 0.5413 - val_accuracy: 0.7365
Epoch 70/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7385 - val_loss: 0.5406 - val_accuracy: 0.7346
Epoch 71/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7383 - val_loss: 0.5430 - val_accuracy: 0.7341
Epoch 72/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7387 - val_loss: 0.5418 - val_accuracy: 0.7349
Epoch 73/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7392 - val_loss: 0.5431 - val_accuracy: 0.7365
Epoch 74/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7388 - val_loss: 0.5417 - val_accuracy: 0.7354
Epoch 75/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7391 - val_loss: 0.5406 - val_accuracy: 0.7346
Epoch 76/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7383 - val_loss: 0.5404 - val_accuracy: 0.7336
Epoch 77/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7368 - val_loss: 0.5410 - val_accuracy: 0.7370
Epoch 78/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7379 - val_loss: 0.5408 - val_accuracy: 0.7349
Epoch 79/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7381 - val_loss: 0.5411 - val_accuracy: 0.7365
Epoch 80/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7385 - val_loss: 0.5419 - val_accuracy: 0.7341
Epoch 81/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7391 - val_loss: 0.5408 - val_accuracy: 0.7367
Epoch 82/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7378 - val_loss: 0.5407 - val_accuracy: 0.7359
Epoch 83/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7385 - val_loss: 0.5393 - val_accuracy: 0.7352
Epoch 84/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7384 - val_loss: 0.5414 - val_accuracy: 0.7352
Epoch 85/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7374 - val_loss: 0.5427 - val_accuracy: 0.7339
Epoch 86/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7389 - val_loss: 0.5402 - val_accuracy: 0.7357
Epoch 87/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7383 - val_loss: 0.5425 - val_accuracy: 0.7370
Epoch 88/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7394 - val_loss: 0.5419 - val_accuracy: 0.7354
Epoch 89/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7394 - val_loss: 0.5411 - val_accuracy: 0.7367
Epoch 90/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7382 - val_loss: 0.5411 - val_accuracy: 0.7357
Epoch 91/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7385 - val_loss: 0.5419 - val_accuracy: 0.7365
Epoch 92/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7389 - val_loss: 0.5403 - val_accuracy: 0.7372
Epoch 93/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7396 - val_loss: 0.5393 - val_accuracy: 0.7378
Epoch 94/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7389 - val_loss: 0.5422 - val_accuracy: 0.7362
Epoch 95/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7392 - val_loss: 0.5398 - val_accuracy: 0.7372
Epoch 96/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7394 - val_loss: 0.5398 - val_accuracy: 0.7328
Epoch 97/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7397 - val_loss: 0.5411 - val_accuracy: 0.7359
Epoch 98/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7399 - val_loss: 0.5402 - val_accuracy: 0.7354
Epoch 99/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7389 - val_loss: 0.5428 - val_accuracy: 0.7328
Epoch 100/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7393 - val_loss: 0.5412 - val_accuracy: 0.7354
Epoch 101/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7401 - val_loss: 0.5418 - val_accuracy: 0.7375
Epoch 102/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7387 - val_loss: 0.5393 - val_accuracy: 0.7349
Epoch 103/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7399 - val_loss: 0.5404 - val_accuracy: 0.7352
Epoch 104/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7394 - val_loss: 0.5412 - val_accuracy: 0.7341
Epoch 105/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7390 - val_loss: 0.5403 - val_accuracy: 0.7344
Epoch 106/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7382 - val_loss: 0.5430 - val_accuracy: 0.7352
Epoch 107/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7404 - val_loss: 0.5393 - val_accuracy: 0.7359
Epoch 108/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7395 - val_loss: 0.5405 - val_accuracy: 0.7362
Epoch 109/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7396 - val_loss: 0.5416 - val_accuracy: 0.7354
Epoch 110/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7393 - val_loss: 0.5394 - val_accuracy: 0.7344
Epoch 111/200
684/684 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7391 - val_loss: 0.5410 - val_accuracy: 0.7362
Epoch 112/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7394 - val_loss: 0.5410 - val_accuracy: 0.7362
Epoch 113/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7396 - val_loss: 0.5406 - val_accuracy: 0.7346
Epoch 114/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7398 - val_loss: 0.5414 - val_accuracy: 0.7344
Epoch 115/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7399 - val_loss: 0.5406 - val_accuracy: 0.7359
Epoch 116/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7400 - val_loss: 0.5409 - val_accuracy: 0.7352
Epoch 117/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7399 - val_loss: 0.5409 - val_accuracy: 0.7365
Epoch 118/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7395 - val_loss: 0.5403 - val_accuracy: 0.7367
Epoch 119/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7394 - val_loss: 0.5397 - val_accuracy: 0.7336
Epoch 120/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7398 - val_loss: 0.5412 - val_accuracy: 0.7367
Epoch 121/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7399 - val_loss: 0.5391 - val_accuracy: 0.7359
Epoch 122/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7390 - val_loss: 0.5413 - val_accuracy: 0.7359
Epoch 123/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7404 - val_loss: 0.5434 - val_accuracy: 0.7362
Epoch 124/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7401 - val_loss: 0.5401 - val_accuracy: 0.7380
Epoch 125/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7392 - val_loss: 0.5391 - val_accuracy: 0.7372
Epoch 126/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7406 - val_loss: 0.5406 - val_accuracy: 0.7367
Epoch 127/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7393 - val_loss: 0.5433 - val_accuracy: 0.7372
Epoch 128/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7394 - val_loss: 0.5397 - val_accuracy: 0.7370
Epoch 129/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7407 - val_loss: 0.5428 - val_accuracy: 0.7365
Epoch 130/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7405 - val_loss: 0.5417 - val_accuracy: 0.7352
Epoch 131/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7390 - val_loss: 0.5403 - val_accuracy: 0.7367
Epoch 132/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7397 - val_loss: 0.5387 - val_accuracy: 0.7372
Epoch 133/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7404 - val_loss: 0.5388 - val_accuracy: 0.7362
Epoch 134/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7403 - val_loss: 0.5378 - val_accuracy: 0.7396
Epoch 135/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7407 - val_loss: 0.5412 - val_accuracy: 0.7367
Epoch 136/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7395 - val_loss: 0.5393 - val_accuracy: 0.7354
Epoch 137/200
684/684 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7407 - val_loss: 0.5402 - val_accuracy: 0.7365
Epoch 138/200
684/684 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7404 - val_loss: 0.5387 - val_accuracy: 0.7378
Epoch 139/200

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5601 - accuracy: 0.7265 - 292ms/epoch - 1ms/step
Loss: 0.560135543346405, Accuracy: 0.7265306115150452

In [18]:
# Export our model to HDF5 file
nn.save('/content/AlphabetSoupCharity_Optimisation(Third_Trial).h5')
files.download('/content/AlphabetSoupCharity_Optimisation(Third_Trial).h5')